//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP1_TCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int idbooking { get; set; }
        public System.DateTime moment { get; set; }
        public Nullable<System.Guid> fkMadeBy { get; set; }
        public Nullable<System.Guid> fkPartner { get; set; }
        public string guest { get; set; }
        public int fkCourt { get; set; }
    
        public virtual court court { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
