//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP1_TCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int idComments { get; set; }
        public string text { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<byte> satisfaction { get; set; }
        public int fkUsers { get; set; }
        public int fkCourts { get; set; }
    
        public virtual courts courts { get; set; }
        public virtual users users { get; set; }
    }
}
