//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP1_TCC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<courts> courts { get; set; }
        public virtual DbSet<courts_maintenances> courts_maintenances { get; set; }
        public virtual DbSet<maintenances> maintenances { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<reservations> reservations { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<seasons> seasons { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
