//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP1_TCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public int idPayments { get; set; }
        public int fkUsers { get; set; }
        public int amount { get; set; }
        public string moyen { get; set; }
        public System.DateTime receptionDate { get; set; }
        public byte status { get; set; }
    
        public virtual users users { get; set; }
    }
}
