//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP1_TCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservations
    {
        public int idReservations { get; set; }
        public System.DateTime date { get; set; }
        public int fkReservers { get; set; }
        public int fkGuests { get; set; }
        public int fkCourts { get; set; }
        public int fkSeasons { get; set; }
    
        public virtual courts courts { get; set; }
        public virtual seasons seasons { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
