//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP1_TCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tccmembership
    {
        public int idtccmembership { get; set; }
        public Nullable<System.Guid> fkuser { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public Nullable<int> NPA { get; set; }
        public string phonenumber { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public bool isSiteAdmin { get; set; }
        public bool isTeamLeader { get; set; }
        public bool approved { get; set; }
    
        public virtual NPA NPA1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
